# Generated by Django 6.0.7 on 2026-09-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="domain",
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
